name: 'Find Docker Paths'
description: 'Finds all the paths with a Dockerfile'
inputs:
  path:
    description: 'The path to search below'
    required: false
    default: '.'
  changes:
    description: 'List of changed files to filter by'
    required: false
    default: '[]'
outputs:
  filtered-paths:
    description: 'Filtered paths'

branding:
  icon: 'activity'
  color: 'green'

runs:
  using: 'node16'
  main: 'index.js'


